#!/bin/bash
set -e

# Ordinary we would run the container and get .deb file with `docker cp`,
# but it doesn't work: https://github.com/boot2docker/boot2docker/issues/398.
# The workaround is to run container in the background and download via HTTP.

PORT=8888

# run container in the background
ID=$(docker run -d -p $PORT:$PORT -e HTTP_PORT=$PORT shamrin/osmocom build-in-docker)

# make terminal output visible (in the background)
docker attach $ID &

IP=192.168.59.103

# continuously try to download .deb via HTTP (`build-in-docker` runs the server)
while true; do
  if curl -s $IP:$PORT; then
    filename=$(curl -s $IP:$PORT/osmonitb.deb)
    curl -sO $IP:$PORT/$filename
    ln -s $filename osmonitb.deb
    break
  else
    sleep 0.5
  fi
done
echo .deb package downloaded

# we are done, kill the (background) container
docker kill $ID
