#!/bin/bash
set -e
ID=$(docker run -d -p 8888:8888 shamrin/osmocom build-in-docker)
docker attach $ID &
while true; do
  if curl -sO 192.168.59.103:8888/osmonitb-0.1-amd64.deb; then
    break
  else
    sleep 0.5
  fi
done
echo .deb package downloaded
docker kill $ID
