#!/bin/bash

set -e

INSTDIR=/tmp/installdir
mkdir $INSTDIR

if test -z "$IN_DOCKER"; then
    echo "This script is meant to be run within the fairwaves/osomcom Docker container. Run 'make env' to build it."
    exit 1
fi

# libdbi with sqlite3 driver: because OpenBSC now fails with libdbi in Trusty
cd /root && git clone http://git.code.sf.net/p/libdbi/libdbi \
    && cd libdbi \
    && git checkout libdbi-0.8.3 \
    && autoreconf -i \
    && ./configure --disable-docs && make && make install \
    && make install DESTDIR=$INSTDIR \
    && ldconfig \
    && cd ..
cd /root && git clone http://git.code.sf.net/p/libdbi-drivers/libdbi-drivers \
    && cd libdbi-drivers \
    && git checkout libdbi-drivers-0.8.3.1 \
    && autoreconf -i \
    && ./configure --with-sqlite3 --disable-docs --with-sqlite3-dir=/usr/lib/x86_64-linux-gnu/ \
    && make && make install \
    && make install DESTDIR=$INSTDIR \
    && ldconfig \
    && cd ..

# libosmocore
cd /root && git clone git://git.osmocom.org/libosmocore.git \
    && cd libosmocore \
    && autoreconf -i \
    && ./configure && make && make install \
    && make install DESTDIR=$INSTDIR \
    && ldconfig \
    && cd ..

# libosmo-abis
cd /root && git clone -b fairwaves/master git://git.osmocom.org/libosmo-abis.git \
    && cd libosmo-abis \
    && autoreconf -i \
    && ./configure && make && make install \
    && make install DESTDIR=$INSTDIR \
    && ldconfig \
    && cd ..

# OpenBSC
cd /root && git clone -b fairwaves/master git://git.osmocom.org/openbsc.git \
    && cd openbsc/openbsc/ \
    && autoreconf -i \
    && ./configure && make && make check && make install DESTDIR=$INSTDIR \
    && cd ../..

# OpenBSC config
mkdir -p $INSTDIR/etc/osmocom
cp /root/openbsc.cfg $INSTDIR/etc/osmocom

# runit scripts
cd $INSTDIR
mkdir -p ./etc/sv ./etc/service
echo cp -r /root/sv/* ./etc/sv
cp -r /root/sv/* ./etc/sv
ln -s /etc/sv/osmo-nitb ./etc/service/osmo-nitb
ln -s /etc/sv/lcr ./etc/service/lcr

# lsb init script compatibility
#ln -s /usr/bin/sv /etc/init.d/osmo-nitb
#ln -s /usr/bin/sv /etc/init.d/lcr

# build deb
cd /root && fpm -s dir -t deb -v 0.1 -n osmonitb -C $INSTDIR -d runit -p osmonitb-VERSION-ARCH.deb --after-install /root/after-install usr/local etc

# run web server for .deb downloading, see `build-with-docker` for details
cd /root && python -m SimpleHTTPServer 8888
