#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

set -e

export DEBIAN_FRONTEND=noninteractive

apt-get install -y runit openvpn

dir=$(mktemp -d)
cd $dir

repolink="https://github.com/shamrin/osmonitb-charm"

# get latest release tag and download its .deb package
latest=$(curl -s -o /dev/null -I -w "%{redirect_url}" $repolink/releases/latest | awk -F/ '{print $NF}')
curl -L -O -s $repolink/releases/download/$latest/osmonitb-$latest-amd64.deb
dpkg -i osmonitb-$latest-amd64.deb
