#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

sv restart osmo-nitb

open-port 8888
open-port 3002/tcp
open-port 3003/tcp
for port in $(seq 30000 30030); do
    open-port $port/udp
done
